name: stockmemo
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other nativst app that you embed your Flutter project into.
version: 4.0.0+13


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_messaging: ^10.0.3
  flex_color_scheme: ^3.0.1
  firebase_auth: ^2.0.0
  cloud_firestore: ^2.3.0
  firebase_core: ^1.4.0
  google_mobile_ads: ^0.13.2
  flutter_speed_dial: ^4.1.0
  custom_searchable_dropdown: ^2.0.4
  month_picker_dialog: ^0.4.0
  flutter_widget_from_html: ^0.6.1
  http: ^0.13.3
  dio: ^4.0.0
  get: ^3.24.0
  back_button_interceptor: ^5.0.0
  firebase_analytics: ^8.2.0
  shared_preferences: ^2.0.5
  kakao_flutter_sdk: ^0.6.3
  url_launcher: ^6.0.9
  flutter_dropdown_alert: ^1.0.2
  flutter_native_splash: ^1.2.1
  html_editor_enhanced: ^2.0.0
  sign_in_with_apple: ^3.0.0
  flutter_colorpicker: ^0.4.0
  the_apple_sign_in: ^1.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_native_splash:
  image: assets/images/title.png
  color: "03C04A"

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/KStock.json
    - assets/images/unnamed.png
    - assets/images/aa.png
    - assets/images/bell.png
    - assets/images/banner.png
    - assets/images/title.png
    - assets/images/post.png
    - assets/images/news.png
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Strong
      fonts:
        - asset: assets/fonts/gyeongijae.ttf
    - family: Hanma
      fonts:
        - asset: assets/fonts/gyeongi.ttf
    - family: Nanum
      fonts:
        - asset: assets/fonts/NanumGothic.ttf
    - family: NanumGothic
      fonts:
        - asset: assets/fonts/NanumGothicBold.ttf

  module:
    androidX: true
    androidPackage: www.stockstorage.stockmemo
    iosBundleIdentifier: www.stockstorage.stockmemo
